spring:
    profiles:
        active: dev
    devtools:
        restart:
            enabled: true
    application:
        name: goswift
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/swiftwayz
        username: swiftwayz
        password: swiftwayz#321
    jpa:
        database: POSTGRESQL
        show-sql: false
        hibernate.ddl-auto: none
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
server:
    contextPath: /swift
    port: 8080
    session:
      timeout: 900

liquibase:
    enabled: true
    drop-first: false
    contexts: dev
    change-log: classpath:config/db/changelog/db.changelog-master.xml

logging:
  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type: TRACE

restserver:
  port: 8080
  host: localhost